# Generated by Django 6.0.4 on 2026-04-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descritpion',
            new_name='description',
        ),
    ]
