# Generated by Django 6.0.4 on 2026-04-14 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_rename_descritpion_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('watched', 'Watched'), ('to_watch', 'To Watch')], default='to_watch', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
