# Generated by Django 6.0.4 on 2026-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_alter_movie_title_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, default='/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', max_length=100),
        ),
    ]
